### ISSUE TITLE
Project dependency tree issue with react-scripts eslint version

### ISSUE THREAD

**Issue by 5tormTrooper** [wesbos/eslint-config-wesbos#17]
Just tried this on a clean CRA install, and the console is throwing an error when I try to start the app.

![term-output](https://user-images.githubusercontent.com/4154407/54546468-fd51bc80-49a3-11e9-9fea-c6611e56fd03.png)

## Steps to reproduce

```$ npx create-react-app new project```
cd in, then...
```$ npx install-peerdeps --dev eslint-config-wesbos```
then there's an install using yarn prompt, go past that, successfully installed.
```$ yarn start```
then, WHAM!
![term-output-full](https://user-images.githubusercontent.com/4154407/54546787-b3b5a180-49a4-11e9-9309-768bbeb21594.png)

Running through those instructions solves the issue, so you might want to remove eslint from the peerdeps for new installs.

**Comment by RobEasthope** [comment]
Removing ESlint from the peerdeps will cause issues for the Airbnb linting dependencies as they use a different version of Eslint than react-scripts.

**Comment by wesbos** [comment]
Yeah if we remove eslint it breaks everything else for other projects. not sure why create-react-app has such a specific version but it's all V5, no?

**Comment by EugeneYiminYan** [comment]
A workaround is to not install `"eslint-config-wesbos": "0.0.19"`becasue the package will install `"eslint": "5.16.0"` (the latest version) to node_modules which create-react-app(CRA) currently does not support. CRA currently depends on eslint@5.12.0

The workaround (A little tedious but it works): 

1. Run `npx install-peerdeps --dev eslint-config-wesbos`
1. In `package.json`, change eslint's version to 5.12.0 in the `devDependencies` block
1. In `package.json`, delete `"eslint-config-wesbos": "^0.0.19"` in the `devDependencies` block
1. Create `.eslintrc` under the root directory
1. Copy [Wes Bos's Eslint rules ](https://github.com/wesbos/eslint-config-wesbos/blob/master/.eslintrc.js) from this repository to the newly created `.eslintrc`
(You need to adjust the formatting to JSON file format) [My `.eslintrc` example](https://github.com/EugeneYiminYan/react-bootcamp-2019/blob/master/s04-create-react-app/first-app/.eslintrc)
1. In `.eslintrc,` Add  `"no-use-before-define": "off",` to `"rules"` block because `serviceWorker.js` violates this rule unless you want to fix or delete the file.
1. Delete `node_modules` and `package-lock.json` then run `npm install`

`package.json`'s devDependencies should look similar to this:

<img width="320" alt="Screen Shot 2019-04-20 at 2 15 10 AM" src="https://user-images.githubusercontent.com/24510019/56454698-374f0f00-6312-11e9-81ca-498d56b8a3f3.png">

`.eslintrc` should look similar to this:

<img width="708" alt="Screen Shot 2019-04-20 at 2 21 53 AM" src="https://user-images.githubusercontent.com/24510019/56454776-163aee00-6313-11e9-8c7a-5557833ce65f.png">

**Comment by lffg** [comment]
Hey guys. This problem is now fixed! See the 3.x CRA changelog to learn more.

**Comment by birksy89** [comment]
Hello, I've just tested this on a fresh install of CRA v3  - and I've managed to get it working...

But it still wasn't 100% smooth for me... Just wanted to check that when people say its "fixed", they too needed to do the following.

Or, if not - I've clearly not done something right :)

(I know the Read Me says you should eject, but I feel historically this thread also hasn't used that approach)

Either way, here's what I did to get it working.

```
npx create-react-app my-app
```
```
npx install-peerdeps --dev eslint-config-wesbos
```
```
yarn start
```
Failed...
![x](https://user-images.githubusercontent.com/4971630/56664323-d4f26780-669f-11e9-919f-391751b3c5b5.PNG)

Followed the steps, as listed in the console:
![y](https://user-images.githubusercontent.com/4971630/56664373-eb98be80-669f-11e9-96f6-adc77e806108.PNG)

Back to our friend - es-lint error:
![x1](https://user-images.githubusercontent.com/4971630/56664475-108d3180-66a0-11e9-9027-4ab34cc5d384.PNG)

Followed same steps as before, to remove the dependency from the tree...

Project now successfully starts the development server...

Finally - To get the rules working, I altered the package.json file to "extend" WesBos:
![z](https://user-images.githubusercontent.com/4971630/56664907-eee07a00-66a0-11e9-8dbe-739df6d344c6.PNG)

Success! 🎉

**Comment by abhijithvijayan** [comment]
@birksy89 Thanks. This actually worked. 

1. After updating `create-react-app`, 
2. Installed `npx install-peerdeps --dev eslint-config-wesbos`
3. Deleted `node_modules` & `package-lock.json`
4. Removed entry for `babel-eslint` from `package.json`
5. Created a `.eslintrc` file at the root
5. Ran `npm install`
6. Changed entry `eslintConfig` to `"extends": "wesbos"`
7. Voila, it works

**Comment by acnicolasdc** [comment]
Hey guys... I found the problem, these steps work for me.

1. Go to global node_modules ( in my case, the route is this: `cd /~`)
2. Delete `node_modules` and `package-lock.json`
3. Install node  LTS ( for me 10.16...)
4. create your react project : `npx create-react-app my-app`
5. go to folder cd `my-app` and RUN `npm start`!

Cheers !

**Comment by houmark** [comment]
@wesbos would you revisit this? It seems that create-react-app now uses babel-eslint 10.0.1, so could you maybe bump it back up again? Should not be 10.0.2 (which is the latest). In fact, I think you have to pin it for 10.0.1 to prevent issues.

I've been messing around for the last hour with this and I even tried forking the rep to adjust the version myself, but when I try to install my fork using npx I get a different (unrelated) error.

The hotfix for me was adjusting package.json and pinning that package in devDependencies to 10.0.1 but it would be nicer if that's not needed.

This broke my automatic cloud deployment, but after the version change, it runs again without issues (cloud runs create-react-app).

**Comment by abhijithvijayan** [comment]
@houmark I forked this config and added a few more linting config & upgraded the packages which supports the latest create-react-app (tested).

The package is published under https://www.npmjs.com/package/eslint-config-onepass

You can view the rules [here](https://github.com/onepassapp/eslint-config-onepass/blob/master/.eslintrc.js)

If you want to try this one
`npx install-peerdeps --dev eslint-config-onepass
`

**Comment by houmark** [comment]
I'm testing it out @abhijithvijayan - thanks!

It looks like `babel-eslint` is available in 10.0.2, but I guess there's no way to get that without breaking `create-react-app`. `eslint` is also available in 6.1.0 but we are locked in for 5.16.0 and the same with a few more eslint plugins.

**Comment by abhijithvijayan** [comment]
@houmark The latest release 2.0.1 locks down babel-eslint to 10.0.1. I will push it to repo later, but the release is all set.

**Comment by phifa** [comment]
Anyone got this working? facing the same issue.

**Comment by abhijithvijayan** [comment]
@phifa Try this

https://github.com/wesbos/eslint-config-wesbos/issues/17#issuecomment-513640120

**Comment by phifa** [comment]
Anybody got this working? Running into the same issue

**Comment by phifa** [comment]
@abhijithvijayan still facing similar issue, now it looks like this: 
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-eslint": "10.0.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-eslint was detected higher up in the tree:

  /home/phifa/projects/zeptool/apps/zeptool-frontend/node_modules/babel-eslint (version: 10.0.1) 
```

**Comment by abhijithvijayan** [comment]
@phifa I will test it locally and will get back at you.

**Comment by abhijithvijayan** [comment]
@phifa Try with the latest release of https://github.com/onepassapp/eslint-config-onepass
```
npx install-peerdeps --dev eslint-config-onepass@latest
```

Version errors are resolved.

**Comment by muditbhutani** [comment]
Kep trying all the above for 1.5 hour still didn't work. Did npm start instead of yarn start and it worked. For any beginner banging his head try this might work

**Comment by vermad843** [comment]
delete your eslint and babel-eslint file from your node modules from your computer .like this -C:\Users\vishnu\node_modules -delete eslint and babel-eslint file
In your project : 

yarn remove eslint
yarn add --dev eslint@6.1.0

yarn remove babel-eslint
yarn add --dev babel-eslint@10.0.3

**Comment by hugoisrr** [comment]
You might need to remove eslint from your node modules:
`sudo npm uninstall eslint`, then remove the file `package-lock.json` and `node_modules`,
then run the `npm install` on your project and `npm start`

**Comment by nsilverio** [comment]
Hello guys

Did anyone found a solution to this? I have tried the bellow and I'm still getting the same errors.

Thanks 

> Hello, I've just tested this on a fresh install of CRA v3 - and I've managed to get it working...
> 
> But it still wasn't 100% smooth for me... Just wanted to check that when people say its "fixed", they too needed to do the following.
> 
> Or, if not - I've clearly not done something right :)
> 
> (I know the Read Me says you should eject, but I feel historically this thread also hasn't used that approach)
> 
> Either way, here's what I did to get it working.
> 
> ```
> npx create-react-app my-app
> ```
> 
> ```
> npx install-peerdeps --dev eslint-config-wesbos
> ```
> 
> ```
> yarn start
> ```
> 
> Failed...
> ![x](https://user-images.githubusercontent.com/4971630/56664323-d4f26780-669f-11e9-919f-391751b3c5b5.PNG)
> 
> Followed the steps, as listed in the console:
> ![y](https://user-images.githubusercontent.com/4971630/56664373-eb98be80-669f-11e9-96f6-adc77e806108.PNG)
> 
> Back to our friend - es-lint error:
> ![x1](https://user-images.githubusercontent.com/4971630/56664475-108d3180-66a0-11e9-9027-4ab34cc5d384.PNG)
> 
> Followed same steps as before, to remove the dependency from the tree...
> 
> Project now successfully starts the development server...
> 
> Finally - To get the rules working, I altered the package.json file to "extend" WesBos:
> ![z](https://user-images.githubusercontent.com/4971630/56664907-eee07a00-66a0-11e9-8dbe-739df6d344c6.PNG)
> 
> Success! 🎉

**Comment by abhijithvijayan** [comment]
See https://github.com/wesbos/eslint-config-wesbos/issues/17#issuecomment-487132509

**Comment by aboutmydreams** [comment]
I do this in cmd and it worked
```
cd /Users/dengwenhao/node_modules/
➜  node_modules rm -rf ./*
zsh: sure you want to delete more than 100 files in /Users/dengwenhao/node_modules/. [yn]? y
```

**Comment by wallacecamacho** [comment]
the beginning of discredit

**Comment by abhijithvijayan** [comment]
For anyone who bumps into this issue, See https://github.com/wesbos/eslint-config-wesbos/issues/17#issuecomment-487132509

**Comment by sarpik** [comment]
Or you could just upgrade `eslint` to `6.x`, as explained in #42.

It work fine with both @abhijithvijayan's and [mine](https://github.com/sarpik/eslint-config-sarpik#with-create-react-app) forks,
and will even support typescript if you call `eslint` with `--ext js,jsx,ts,tsx`.

**Comment by lucascaton** [comment]
Now that ESLint 7 is out, something similar is happening:

```sh
The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^6.6.0"
```

**Comment by abhijithvijayan** [comment]
Along with that message, CRA shows a way to suppress the warning.

see if that works.

The CRA still uses v6.1.x in their repository, might take a while to migrate.

**Comment by yashgupta18** [comment]
i searched the whole web. Just run 
npm uninstall eslint
in terminal 
it will work fine.

**Comment by mkkeffeler** [comment]
can confirm this fixed that issue.

**Comment by MichaelOlatunji** [comment]
running:
 `yarn uninstall eslint` fixed it for me
then  run `yarn start` , you are good to go

**Comment by Haley-Zhu** [comment]
I have the same issue, I follow the steps: 
![image](https://user-images.githubusercontent.com/45616408/90578591-10a33000-e207-11ea-9287-29d79fd31b81.png)
but if remove the elint, then the script: yarn lint is failed.

**Comment by Asjas** [comment]
Hey @Haley-Zhu,

What version of eslint does CRA say it's expecting? 
It's possible they are still using an older version of eslint which is causing that message 🙂

**Comment by muzhaqi16** [comment]
I am having the same issue, I have the react app under a folder inside of a node.js application. I don't have eslint installed inside the react app folder but I do have it in the main folder.

**Comment by andrewhwanpark** [comment]
Does anyone know how to fix this issue for eslint 7.7.0? If I delete the eslint devDependencies as told by the terminal script, then I can't use eslint in VScode. But then again, the script warns us against manually installing 6.6.0... quite a dilemma

**Comment by andrewhwanpark** [comment]
For yarn users having the same issue with eslint 7.7.0:

rm yarn.lock && rm -rf node_modules && yarn

this fixed the issue for me.

**Comment by Ownmarc** [comment]
this is happening when I do `npm start` : 

![image](https://user-images.githubusercontent.com/24617457/92198783-4e2ccd80-ee43-11ea-8059-13ed93c423ba.png)

**Comment by wesbos** [comment]
I've tested this and it seems to be fixed with the latest combo of eslint / wesbos / react-scripts

**Comment by RAJVGN** [comment]
Add this into .env file. 
SKIP_PREFLIGHT_CHECK=true
then
npm run start

**Comment by eglove** [comment]
This seems to be a common recurring problem. It doesn't work currently. I assume there is no permanent fix.

**Comment by xrzhuang** [comment]
I haven't been able to find a solution to this. I ran create react app with the typescript template. Then followed this tut https://medium.com/react-courses/react-create-react-app-v3-4-1-a55f3e7a8d6d. I ended up turning off skip_preflight_check as nothing else has worked for me.

**Comment by denven** [comment]
I experienced the two issues separately:

1. How I fixed the **"eslint ^6.6.0"** dependency:
```bash
sudo npm uninstall -g eslint   # remove it temporarily 
rm -rf /home/username/node_modules/eslint/  # I have to delete the directory manually
m -rf node_modules
yarn && yarn build 
```

2. How I fixed the **"babel-eslint ^10.0.1"** error:

I just fixed it by following the message hint, put `SKIP_PREFLIGHT_CHECK=true` in a `.env` file.

**Comment by mthomas100** [comment]
I resolved this issue through
`rm -rf node_modules rm-rf yarn.lock
yarn
`
and in vscode cmd + shift + p "Restart ESlint Server"

**Comment by handhikadj** [comment]
Having this issue on a nested react project using latest eslint and wesbos eslint config

for example:
```
-- myproject
----firstreactproject <-- this works fine
----secondreactporject <-- I have to set SKIP_PREFLIGHT_CHECK to true so that I don't get the error
```

**Comment by Heeeesung** [comment]
> I resolved this issue through `rm -rf node_modules rm-rf yarn.lock` `yarn`
> 
> and in vscode cmd + shift + p "Restart ESlint Server"

Nothing else worked, this one works
thanks 😀

**Comment by gusaaaaa** [comment]
I tried everything. Finally solved it by updating react-scripts version to 5.0.1 in package.json.

I was getting:

`The react-scripts package provided by Create React App requires a dependency:

  "eslint": "5.12.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  [project_folder]/node_modules/eslint (version: 8.20.0)`

The weird part was that I followed the instructions and confirmed that the eslint version installed in /node_modules was 5.12.0. I assume that's the version installed by the older version of react-scripts.

Btw, why would react-scripts ship with eslint?

**Comment by Asjas** [comment]
"Btw, why would react-scripts ship with eslint?"

>One Dependency: There is only one build dependency. It uses webpack, Babel, ESLint, and other amazing projects, but provides a cohesive curated experience on top of them.

`react-scripts` has always shipped `ESLint`. It's an included dependency 🙂

https://github.com/facebook/create-react-app#philosophy

**Comment by macknilan** [comment]
@gusaaaaa thanks it work for me
> I tried everything. Finally solved it by updating react-scripts version to 5.0.1 in package.json.
